CREATE TABLE seriesstatrecords ( 
  series int4 NOT NULL,
  season int4 NOT NULL,
  reportingteamid int4 NOT NULL, 
  statsteamid int4 NOT NULL,
  playerid int4 NOT NULL, 
  games int4 DEFAULT 0, 
  bat_ab int4 DEFAULT 0, 
  bat_runs int4 DEFAULT 0, 
  bat_hits int4 DEFAULT 0, 
  bat_rbi int4 DEFAULT 0, 
  bat_hr int4 DEFAULT 0, 
  bat_doubles int4 DEFAULT 0, 
  bat_triples int4 DEFAULT 0, 
  bat_walks int4 DEFAULT 0, 
  bat_strikeouts int4 DEFAULT 0, 
  bat_sb int4 DEFAULT 0, 
  bat_cs int4 DEFAULT 0, 
  errors int4 DEFAULT 0, 
  pitch_gs int4 DEFAULT 0, 
  pitch_cg int4 DEFAULT 0, 
  pitch_sho int4 DEFAULT 0, 
  pitch_wins int4 DEFAULT 0, 
  pitch_loss int4 DEFAULT 0, 
  pitch_save int4 DEFAULT 0, 
  pitch_ip int4 DEFAULT 0, 
  pitch_hits int4 DEFAULT 0, 
  pitch_er int4 DEFAULT 0, 
  pitch_walks int4 DEFAULT 0, 
  pitch_strikeouts int4 DEFAULT 0, 
  pitch_hr int4 DEFAULT 0, 
  pitch_ipfull int4 DEFAULT 0, 
  pitch_ipfract int4 DEFAULT 0, 
  CONSTRAINT pk_statrecords PRIMARY KEY (playerid, series, season, reportingteamid)
) WITH OIDS;
REVOKE ALL ON TABLE seriesstatrecords FROM PUBLIC;
GRANT ALL ON TABLE seriesstatrecords TO sbaapba;
