insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (25, 1, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (31, 1, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (1,  1, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (3,  1, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (36, 2, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (30, 1, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (16, 2, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (35, 1, 2013, 1, 0, 0,0, 0, 0, 0, 0);

insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (13, 2, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (14, 2, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (29, 2, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (15, 2, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (7,  3, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (10, 3, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (8,  3, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (26, 3, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (11, 3, 2013, 1, 0, 0,0, 0, 0, 0, 0);
insert into teamresults (teamid, divisionid, year, leagueid, won, lost, divisionwin, divisionloss, divisiontitle, worldseriesapp, worldserieswin) values (9,  3, 2013, 1, 0, 0,0, 0, 0, 0, 0);
